name: Checks
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - develop
      - master

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Setup npm" # Add our registry to npm config
        run: | # Custom action
          npm set @tkssharma:registry=https://npm.pkg.github.com/tkssharma
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
      - name: Install dependencies
        run: |
          npm ci
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npx lerna exec npm run test
