name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - develop
      - main
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 16"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Version and publish" # Interesting step
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

          if [ ${{ github.base_ref }} = development ]; then
            npm run version:prerelease:ci--yes
          else
            npm run version:ci
          fi
          npm run generate:ci
          npm run release:ci
